export const MODULE_NAME = 'resources';

export const STORE_ENTITIES = `${MODULE_NAME}/STORE_ENTITIES`;
export type STORE_ENTITIES = typeof STORE_ENTITIES;

export const RESOURCE_QUERIED = `${MODULE_NAME}/RESOURCE_QUERIED`;
export type RESOURCE_QUERIED = typeof RESOURCE_QUERIED;

// export const QUERY_CHANGED = `${MODULE_NAME}/QUERY_CHANGED`;
// export type QUERY_CHANGED = typeof QUERY_CHANGED;

export const QUERY_RESULT_CHANGED = `${MODULE_NAME}/QUERY_RESULT_CHANGED`;
export type QUERY_RESULT_CHANGED = typeof QUERY_RESULT_CHANGED;
