export const MODULE_NAME = 'endpoints';

export const ENDPOINT_TEMPLATES_FULFILLED = `${MODULE_NAME}/READ_TEMPLATES_FULFILLED`;
export type ENDPOINT_TEMPLATES_FULFILLED = typeof ENDPOINT_TEMPLATES_FULFILLED;
